config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'articles/new'
  get 'articles/show'
  get 'articles/edit'
  get 'articles/_form'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_path(@article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="form-group">
  <%= form_for(@article) do |a| %>
    <%= a.label :title %>
    <%= a.text_area :title %>
    <%= a.label :content %>
    <%= a.text_area :content %>
    <%= a.submit class:"btn btn-info" %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>
<%= link_to "Back", articles_path %>

app/views/articles/index.html.erb
<div class="navbar">
  <p>Wikinimous</p>
  <p><%= link_to "New Article", new_article_path %></p>
</div>

<% @articles.each do |a| %>
<p><%= link_to a.title, article_path(a) %></p>
<p><%= a.content %></p>
<% end %>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>
<%= link_to "Back", articles_path %>

app/views/articles/show.html.erb
<div class="edit">
  <h2><%= @article.title %></h2>
  <p><%= @article.content %></p>

  <%= link_to edit_article_path(@article) do %>
  <i class="far fa-edit"></i>
  <% end %>

  <%= link_to article_path(@article),
    method: :delete,
    data: { confirm: "confirm your delete?" } do %>
  <i class="far fa-trash-alt"></i>
  <% end %>

  <%= link_to "Back", articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>